### ISSUE TITLE
[User Story] Sign up

### ISSUE THREAD

**Issue by paulio11** [paulio11/P5-Pokebox#1]
As a **new user** I can:

**Sign up**, so that I can have my own account and use the full feature set of the website

**Tasks:**

- [x] Build sign up form
- [x] Username field
- [x] Password field
- [x] Confirm password field
- [x] Redirect user to login

**Acceptance Criteria:**

- [x] Check database or back-end admin for a new user sign up
- [x] Check they have a profile created
- [x] Test login with new user username and password
- [x] Once signed up i am redirected to the login page
