### ISSUE TITLE
[User Story] Remove Pokémon

### ISSUE THREAD

**Issue by paulio11** [paulio11/P5-Pokebox#12]
As a **registered user** I can:

**Remove Pokémon from my collection**, so I can update my collection if necessary

**Tasks:**

- [x] Conditionally render a button on the pokemon's information page that shows add or remove from collection based on fetched profile data.
- [x] Create a function that updates the Pokémon array with the ID of the viewed Pokémon, adding or removing.

**Acceptance Criteria:**

- [x] Check collected status is reflected correctly on the pokemon's information page
- [x] Check the updated collection is correct on the user's profile page
