### ISSUE TITLE
[User Story] Display my Pokémon

### ISSUE THREAD

**Issue by paulio11** [paulio11/P5-Pokebox#13]
As a **registered user** I can:

**Display my Pokémon collection**, so I can share it with other users

**Tasks:**

- [x] Use the function created to fetch and display the Pokémon list but instead pass it the Pokémon array in the user profile as the list.
- [x] Pass the data to the Pokémon component to display the pokemon's name, id and sprite
- [x] Make use of infinite scroll if collection is large

**Acceptance Criteria:**

- [x] A user's Pokémon collection is loaded and displayed
- [x] Each Pokémon is rendered using the Pokémon component
- [x] React infinite scroll loads more data when the page is scrolled
