### ISSUE TITLE
[User Story] Collection progress

### ISSUE THREAD

**Issue by paulio11** [paulio11/P5-Pokebox#14]
As a **registered user** I can:

**See how many Pokémon I have**, so I can keep track of my progress (percentage and number of)

**Tasks:**

- [x] Use the col_size value from the profile data to work out collection percentage
- [x] Use bootstrap progress bar to display collection progress
- [x] Include a percent value
- [x] Use on trainer card (trainer list page) and on a user's profile page

**Acceptance Criteria:**

- [x] Progress bar displays correctly for each user
- [x] Shows correct value
