### ISSUE TITLE
[User Story] Post create

### ISSUE THREAD

**Issue by paulio11** [paulio11/P5-Pokebox#15]
As a **registered user** I can:

**Post a new entry in my dairy**, so I can share something new

**Tasks:**

- [x] Create a form with fields for a new post
- [x] Send form data to posts api endpoint with a post request
- [x] Redirect user to that created post's page

**Acceptance Criteria:**

- [x] Created form shows errors if necessary and correctly validates all data
- [x] Both text and image are posted correctly
- [x] User is successfully redirected to the created post's page
