### ISSUE TITLE
[User Story] Post edit

### ISSUE THREAD

**Issue by paulio11** [paulio11/P5-Pokebox#16]
As a **registered user** I can:

**Edit my posts**, so that I can change them if necessary

**Tasks:**

- [x] Copy new post form page and adjust accordingly 
- [x] Fetch post data from api to display inside form
- [x] Make patch request to api endpoint to update post
- [x] Redirect user back to post

**Acceptance Criteria:**

- [x] The right post data is displayed on the edit post form
- [x] All form fields are validated 
- [x] Saving changes updates the post
- [x] Redirected to correct post showing new changes
