### ISSUE TITLE
[User Story] Post delete

### ISSUE THREAD

**Issue by paulio11** [paulio11/P5-Pokebox#17]
As a **registered user** I can:

**Delete my posts**, so that I can remove them if necessary

**Tasks:**

- [x] Add button for delete
- [x] Button brings up a modal for confirmation
- [x] The delete button in the modal sends delete request to api
- [x] Redirect to profile

**Acceptance Criteria**

- [x] The button to show the modal and close the modal both work
- [x] Delete button removes the post object
- [x] User is redirected
