### ISSUE TITLE
[User Story] Post image

### ISSUE THREAD

**Issue by paulio11** [paulio11/P5-Pokebox#18]
As a **registered user** I can:

**Add an image to my post**, so that I can share an image

**Tasks:**

- [x] Include a file input in both new post and edit post forms
- [x] Conditionally display the image in the post component if it exists

**Acceptance Criteria**

- [x] File input has validation
- [x] Post image is shown when there is one available in second column
- [x] If no post image available post is displayed in only one column
