### ISSUE TITLE
[User Story] Like/unlike

### ISSUE THREAD

**Issue by paulio11** [paulio11/P5-Pokebox#19]
As a **registered user** I can:

**Like / unlike someone else's post**, so that I can show my support

**Tasks:**

- [x] Create function to create like ID and send post request to like endpoint
- [x] Create function to delete like object and send delete request to the like ID
- [x] Conditionally render either a like or unlike button based on presence of a like ID
- [x] Restrict like functionality if user is post owner or logged out
- [x] Increase or decrease the parent posts like count 

**Acceptance Criteria**

- [x] If the user has liked the post, the button is shown as a pink heart, and they are able to unlike
- [x] If the user has not liked the post, the button is shown as just an outline, and they are able to like
- [x] If I'm logged on as the post owner I am unable to like, tooltip reflects this
- [x] Like is created or deleted in the database
- [x] Like count on parent post either goes up or down
