### ISSUE TITLE
[User Story] Sign in

### ISSUE THREAD

**Issue by paulio11** [paulio11/P5-Pokebox#2]
As a **logged out user** I can:

**Sign in**, so that I can return to my account

**Tasks:**

- [x] Build login for connected the back-end login endpoint.
- [x] Build a current user context to store the state of the current user
- [x] Redirect user to their profile

**Acceptance Criteria:**

- [x] Use conditional rendering to show user they are logged in.
- [x] Visiting the user endpoint to confirm login was successful.
- [x] User is redirected to their profile page after login
