### ISSUE TITLE
[User Story] Comment on post

### ISSUE THREAD

**Issue by paulio11** [paulio11/P5-Pokebox#20]
As a **registered user** I can:

**Comment on a post**, so that I can start or add to a conversation related to the post

**Tasks:**

- [x] Create comment form component
- [x] Include on post page
- [x] Display if there is a user logged in only
- [x] Send post request to comment end point when submitted
- [x] Increase comment count of parent post

**Acceptance Criteria**

- [x] Comment form has validation
- [x] Typed comment is successfully posted
- [x] Comment data updated instantly
- [x] Post comment count goes up by 1
- [x] Comment exists in database
