### ISSUE TITLE
[User Story] Comment edit

### ISSUE THREAD

**Issue by paulio11** [paulio11/P5-Pokebox#21]
As a **registered user** I can:

**Edit my comments**, so that I can change what I said

**Tasks:**

- [x] Create a comment edit form component, a copy of the new comment form
- [x] Fetch comment data to display in form
- [x] Display edit button on comment if the logged in user is the owner of the comment
- [x] Edit button hidden if no user or another user
- [x] Conditionally render edit form in the place of the comment when button is clicked
- [x] Send form data with a patch request to the comment ID endpoint

**Acceptance Criteria**

- [x] Text input is correctly validated
- [x] If I'm logged in as the owner i can see the edit comment button
- [x] I can't see the edit button anyone else's comments
- [x] Clicking the button shows the edit form
- [x] Saving changes correctly displays changes and patches the database
