### ISSUE TITLE
[User Story] Log out

### ISSUE THREAD

**Issue by paulio11** [paulio11/P5-Pokebox#23]
As a **logged in user** I can:

**Log out**, so that my account remains secure and private when not in use

**Tasks:**

- [x] Add log out link to navbar, shown only to logged in users
- [x] Create log out function to send a post request to logout endpoint
- [x] Set the current user to null
- [x] Redirect back to home page

**Acceptance Criteria**

- [x] Logout link renders only for logged in users
- [x] Logout link logs out user
- [x] API user endpoint shows no logged in user
- [x] Redirected to home page
