### ISSUE TITLE
[User Story] Password change

### ISSUE THREAD

**Issue by paulio11** [paulio11/P5-Pokebox#25]
As a **registered user** I can:

**Change my password**, so that my account can remain secure

**Tasks:**

- [x] Create a settings page
- [x] Create a password change form with fields: old password, password1, and password2
- [x] Create an update password function that posts the data to the password/change endpoint

**Acceptance Criteria**

- [x] All errors are reported to the user
- [x] All forms have validation
- [x] Password change form successfully changes the users password
