### ISSUE TITLE
[User Story] Search (logged out)

### ISSUE THREAD

**Issue by paulio11** [paulio11/P5-Pokebox#3]
As a **logged out user** I can:

**Search Pokébox**, so that I can find other trainers and/or Pokémon that I am looking for

**Tasks:** 

- [x] Build search form
- [x] Search input used as query and changes pokeapi fetch url
- [x] Show error if no results or 404 from pokeapi

**Acceptance Criteria:**

- [x] Test search works with a known Pokémon
- [x] Test searching for a Pokémon that doesnt exist
- [x] Searched Pokémon shows up
- [x] An error is shown when there are no results
- [x] Updating the query shows the loader
