### ISSUE TITLE
[User Story] Trainer List

### ISSUE THREAD

**Issue by paulio11** [paulio11/P5-Pokebox#39]
As a **user** I can:

**See a list of all registered "trainers"**, so I can view their profiles and compare myself to them.

**Tasks:**

- [x] Build a page to show a list of trainers
- [x] Fetch data from the trainers api endpoint
- [x] Pass data to the trainer component for each trainer to show their data
- [x] Link to their profile
- [x] Make use of react infinite scroll

**Acceptance Criteria**

- [x] The correct data is loaded and displayed
- [x] Scrolling down the page loads more trainer data
- [x] Each trainer is represented by the trainer component
- [x] Clicking takes you to the correct profile page
