### ISSUE TITLE
[User Story] View Pokémon List

### ISSUE THREAD

**Issue by paulio11** [paulio11/P5-Pokebox#4]
As a **user** I can:

**View all the Pokémon**, so that I can see what is available

Tasks:

- [x] Create function to get data from pokeapi
- [x] Use the fetched urls to again fetch data for each Pokémon
- [x] Pass the data to a component to display the name, id and sprite
- [x] Make use of infinite scroll

Acceptance Criteria:

- [x] List of Pokémon loads correctly
- [x] The information displayed includes the sprite, id and name
- [x] Scrolling loads more Pokémon
