### ISSUE TITLE
[User Story] Profile Search

### ISSUE THREAD

**Issue by paulio11** [paulio11/P5-Pokebox#43]
As a **user** I can:

**Search for other users**, so that I can find who I am looking for.

**Tasks:**

- [x] Add search form to trainer list page
- [x] Use query to send get request to api trainers endpoint
- [x] Display list of results
- [x] Show no results if necessary

**Acceptance Criteria:**

- [x] Search form on page sends the correct query to api endpoint
- [x] Search results are correctly displayed
- [x] If no results are found an error message is shown
