### ISSUE TITLE
[User Story] Profile sorting

### ISSUE THREAD

**Issue by paulio11** [paulio11/P5-Pokebox#44]
As a **user** I can:

**Sort a list of users by collection completion**, so I can see who is the best trainer!

**Tasks:**

- [x] Create forms to display two dropdowns
- [x] Order by ascending and descending dropdown
- [x] Sort by Pokémon collection, join date, username dropdown
- [x] Create function to handle sort change
- [x] Update API request with output from sort change function

**Acceptance Criteria**

- [x] All possible sorts and orders load the correct data
