### ISSUE TITLE
[User Story] Profile Page

### ISSUE THREAD

**Issue by paulio11** [paulio11/P5-Pokebox#45]
As a **user** I can:

**View someone else's or my own profile page**, so I can see my information or someone else's.

**Tasks:**

- [x] Create a profile page component
- [x] Fetch data from the profile endpoint based on the id in the url
- [x] Display all profile data
- [x] Display a users diary entries
- [x] Display a users Pokémon collection

**Acceptance Criteria**

- [x] Correct profile data loads
- [x] All information is presented
- [x] A user's posts are fetched and displayed using the post component
- [x] A user's Pokémon collection is fetched and displayed using the Pokémon component
