### ISSUE TITLE
[User Story] Diary Posts

### ISSUE THREAD

**Issue by paulio11** [paulio11/P5-Pokebox#48]
As a **user** I can:

**View my own or other user's diary posts**, so that I can see what they are sharing.

**Tasks:**

- [x] Load and display a user's diary posts on their profile page
- [x] Represent each post with the post component
- [x] Make use of react infinite scroll

**Acceptance Criteria**

- [x] The correct posts are shown in the correct order on the correct user's profile page
- [x] Scrolling loads more posts
