### ISSUE TITLE
[User Story] View Pokémon

### ISSUE THREAD

**Issue by paulio11** [paulio11/P5-Pokebox#6]
As a **user** I can:

**View a specific Pokémon**, so I can see more information including stats, a description, images and types

**Tasks:**

- [x] Create a page to show Pokémon data
- [x] Fetch data for that Pokémon using the Pokémon and Pokémon-species pokeapi endpoint
- [x] Display relevant data
- [x] Include back and next buttons to navigate between Pokémon

**Acceptance Criteria:**

- [x] Correct Pokémon information is displayed
- [x] Information displayed includes: name, id, official artwork, genus text, pokedex entry, types and Pokémon stats.
- [x] Back button loads the previous pokemons information
- [x] Next button loads the next pokemons information
