### ISSUE TITLE
[User Story] Profile avatar

### ISSUE THREAD

**Issue by paulio11** [paulio11/P5-Pokebox#7]
As a **registered user** I can:

**Upload an avatar**, so it can represent me as a user

**Tasks:**

- [x] Display avatar to the user where necessary
- [x] Implement a user = owner check to show an edit button if true
- [x] Build a form with a file input so a user can select a new avatar
- [x] Put/Patch new profile data with avatar from the form

**Acceptance Criteria:**

- [x] User avatar correctly displayed
- [x] Edit avatar button shown if user is the profile owner
- [x] Image included in the form data becomes the new user avatar
