### ISSUE TITLE
[User Story] Profile favourite Pokémon

### ISSUE THREAD

**Issue by paulio11** [paulio11/P5-Pokebox#9]
As a **registered user** I can:

**Set my favourite Pokémon**, so that I can show other users who I like

**Tasks:**

- [x] Use Pokémon component to display a users favourite Pokémon on their profile
- [x] Add button to Pokémon information page that either: 1) shows that the Pokémon is their favourite, or 2) when clicked makes the current Pokémon their new favourite
- [x] This sends patch request to the profile endpoint

**Acceptance Criteria:**

- [x] Correct Pokémon displayed on user's profile
- [x] Conditionally rendered button on Pokémon page reflects favourite status if viewed Pokémon is the favourite
- [x] Clicking the button sets as new favourite, this can be checked by refreshing the page or visiting the user's profile
